KIA-PROGRAMMING-38/JKC-FallguysProject

README.md

- README.me 파일이 업데이트 되었습니다
- 게임의 목적이 추가되었습니다
- 타겟 플랫폼이 추가되었습니다

[Chore] README.me 파일 업데이트

---

JKC_Fallguys/Assets/Jinsoo/DataManager.cs
JKC_Fallguys/Assets/Jinsoo/DataManager.cs.meta

- 데이터매니저 static 클래스를 구현하였습니다
- 리소스를 로드하기 위해 Resources 라이브러리를 사용하기 위해 데이터매니저 클래스를 사용할 수 있습니다
- 전역적으로 접근하기 위해 static으로 구현하였습니다
- 데이터 바인딩을 위한 경로를 반환하는 함수를 작성하였습니다
> params string[] 인자로 받는 함수를 작성하였습니다
string.Join을 사용하였습니다
- #17
---
- 함수는 하나의 일만 …

[Feat] DataManager 구현

---

JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/JumpStartState.cs
JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/JumpSubState.cs
JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/JumpingState.cs
JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/PlayerPhysicsController.cs

- 점프 키를 누르면 Player Character가 위로 힘을 주어 점프합니다.
- Player Physics Controller에서 Jump로직과 Jump하는 중에 공중에서 인풋에 따라 움직일 수 있게합니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/7fbd0bd5-a32d-477f-9157-1a641368148f
- #24

[Feat] Player Jump

---

JKC_Fallguys/Assets/Huiji/Character/Player.controller
JKC_Fallguys/Assets/Huiji/Player.unity
JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/FallState.cs
JKC_Fallguys/Assets/Huiji/Scripts/HuiJi_Player/PlayerPhysicsController.cs
JKC_Fallguys/ProjectSettings/TagManager.asset

- Player가 Boundary또는 일정 이상 힘의 충돌을 할시 Fall 상태로 전환합니다.
- Fall 상태는 어느 상태이던지 전이할수 있습니다.
- Fall 상태에서는 Freeze Rotation을 해제하는 것으로 넘어짐을 표현했습니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/70bdc5ff-b867-4bed-991d-60b3010376ce
- #27

[Feat] Player Fall

---

JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/0/4/0404ff141f47528a4473aa4c393fc61d4db7f8cd
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/2/c/2c2ec2c0b3ddce4eb5c6d192dcc4dfd1aafe2121
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/5/d/5dd8818e4ba2a03a15aec95a2064ed21850feb80
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
JKC_Fallguys/Assets/Jinsoo/02/LineEffect.cs
JKC_Fallguys/Assets/Jinsoo/02/LineEffectPool.cs
JKC_Fallguys/Assets/Jinsoo/02/LineEffectPooler.cs
JKC_Fallguys/Assets/Jinsoo/02/MatchingStandbySceneInitializer.cs
JKC_Fallguys/Assets/Jinsoo/02/RespawnZone.cs
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/Object/ReleaseZone.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/CurrentParticipantsViewController.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/CurrentParticipantsViewController.prefab.meta
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/EnterLobbyFromMatchingViewController.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/EnterLobbyFromMatchingViewController.prefab.meta
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/ReturnButtonViewController.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/ReturnButtonViewController.prefab.meta
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/RotaitionFaceIconViewController.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/02_MatchingStandby/UI/RotaitionFaceIconViewController.prefab.meta

- 이제 씬이 로드되면, 맵에 존재하는 오브젝트들이 동적으로 생성됩니다
- 맵에 존재하는 오브젝트들이 동적으로 생성됩니다
> MatchingStandby Scene Initializer 에서 씬이 시작되고 생성해줍니다
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005202/89da7586-3cf0-4d26-8320-d48f5d93b9b6
- #39 
---
- 코드만으로는 이해하기 어려운 부분에 주석이 작성되어 …

[Refactor] MatchingStandby 씬 오브젝트 동적 생성으로 로직 변경

---

JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/5/c/5c5bc0d39135aed76ba733b560bf6a3b833a104b
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/6/9/69c27d42348296689e26bf1aa589ad086a683d02
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/b/8b16bbca315bda14140d116038cc005dbb9a95dd
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/9/9/991709d3b53136135e2184b786275fbd923b247b
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/a/a/aa558f467190a1b07ec86abf53665c17379e5e88
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
JKC_Fallguys/Assets/1_Scripts/Player/CameraAngle.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerInput.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
JKC_Fallguys/Assets/Huiji/Scenes/06_GameResult.unity
JKC_Fallguys/Assets/Resources/Prefabs/FruitChute/MapFruitChute.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab
JKC_Fallguys/Assets/_legendHoop.unitypackage.meta
JKC_Fallguys/Assets/fruitchute_.unitypackage.meta
JKC_Fallguys/ProjectSettings/ProjectSettings.asset
JKC_Fallguys/ProjectSettings/TagManager.asset

- 
- 이제 네트워크에서 다른 사람들의 캐릭터 움직임이 동기화됩니다
- photonView.IsMine 이용
> 플레이어 캐릭터 스크립트에 photonView.IsMine의 코드가 추가되었습니다
- #83

[Refactor] 캐릭터의 스크립트에 photonView.IsMine를 추가

---

JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
JKC_Fallguys/Assets/Huiji/Scripts/UI/EnterLobbyFromStage.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/EnterLobbyFromStage/StageExitPanelViewController.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/EnterLobbyFromStage/StageExitPanelViewController.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/ExitButton.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/ExitButton/ExitButtonPresenter.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/ExitButton/ExitButtonPresenter.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/ExitButton/ExitButtonView.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/ExitButton/ExitButtonView.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/ExitButton/ExitButtonViewController.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/ExitButton/ExitButtonViewController.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/StageSceneModel.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/StageSceneModel.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/StageStartPresenter.cs
JKC_Fallguys/ProjectSettings/ProjectSettings.asset

- Exit Button을 클릭하면 Exit Panel이 활성화됩니다.
- 버튼을 누를 수 있는지 여부를 확인하는 bool 변수와 panel을 띄우는 것을 결정하는 bool변수를 Model에 둡니다.
> Presenter는 Model의 bool 변수를 확인해서 둘다 true가 되면 ExitPanel을 활성화합니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/6b0a7cb7-3b89-4ebf-ae50-9939a2de6ebb
- #80

[Feat] ExitButton

---

JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelPresenter.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelPresenter.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelView.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelView.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelViewController.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/GoalPanelViewController.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/StageModel.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/Stage/StageModel.cs.meta
JKC_Fallguys/Assets/Resources/UI/03_Stage/Tips.png.meta
JKC_Fallguys/Assets/_legendHoop.unitypackage.meta
JKC_Fallguys/Assets/fruitchute_.unitypackage.meta

- Goal Panel UI를 구성했습니다.
- MVRP 패턴으로 UI를 관리하기 위해 계층 구조를 아래의 이미지처럼 구성했습니다.
- #79

[Feat] GoalPanel 오브젝트 구성

---

JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterPresenter.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterPresenter.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterView.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterView.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterViewController.cs
JKC_Fallguys/Assets/Huiji/Scripts/UI/EntryCounter/EntryCounterViewController.cs.meta
JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/StageSceneModel.cs
JKC_Fallguys/Assets/Resources/UI/03_Stage/Timer_1.png.meta

- Entry Counter UI에 현재 플레이어의 수와 골에 들어온 플레이어의 수를 나타냅니다.
- Model에 Stage에 입장한 플레이어의 수와 골에 들어온 플레이어의 수를 나타내는 변수를 저장합니다.
> Model에 있는 변수들이 업데이트 되면 Unirx의 기능인 SubscribeToText를 이용하여 변수의 값을 UI의 텍스트로 보여줍니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/933eca22-641f-4217-8c6b-b072e5644974
- #81

[Feat] Entry Counter UI

---

JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/1/c/1c6daf3e2bba29ea86fb5533675be5766c4f7bf7
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/2/e/2e2ffd4cd6e22a13dcaac6ebffa0dfbedd5cd849
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/4/9/49823c243abe0f9e3bedb4f80106a715934a39c7
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/6/3/635a698a027294f08466d09c727361d8f37782f0
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/7/0/708f04e450678fc8c27025bf2706aa062c00ddd2
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/8/b/8b16bbca315bda14140d116038cc005dbb9a95dd
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/9/3/93c5e8b33fa26927edfcc4fbe1bd6524bd860f05
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/9/7/977241db214966ec7e81e6b2ec266de62722e54a
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/a/a/aa558f467190a1b07ec86abf53665c17379e5e88
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/b/d/bd6c77fe73417afa2ba973b9f5eee45c2c0fdac5
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/c/1/c10920d1d8890f02dd236796523e97ecca28f2f5
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/c/8/c89699e79c4a5798b3a5de6c181577e536633d0c
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/d/6/d6ef6ee7d24bb560829d2bf80246960245d5e91f
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/d/7/d77b4e7849842bfba46e0500ffcd892637ca20f6
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/e/2/e2995af3c60f16d3ecc31bc349087798dc66539a
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/f/0/f0bd965074c95c058907f9901f23432ac9f4aa0d
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/issuestore/index.pb
JKC_Fallguys/.idea/.idea.JKC_Fallguys/.idea/sonarlint/securityhotspotstore/index.pb
JKC_Fallguys/Assets/Jinsoo/04_GameLoading/05_GameLoading.unity
JKC_Fallguys/Assets/Jinsoo/04_GameLoading/WhiteScreenPresenter.cs
JKC_Fallguys/Assets/Jinsoo/Test.unity
JKC_Fallguys/Assets/Jinsoo/Test.unity.meta

- GameLoading 씬에서의 Map Information UI가 추가되었습니다
- 계층 창에 게임오브젝트를 추가하였습니다
> Map Information을 나타내기 위해 MapInformationViewController와 하위 오브젝트들을 추가하였습니다
- #71

[Feat] GameLoading 씬의 Map Information UI 화면 게임오브젝트 구성

---

JKC_Fallguys/Assets/Huiji/Scenes/03_RoundResult.unity
JKC_Fallguys/Assets/Huiji/Scenes/03_RoundResult.unity.meta
JKC_Fallguys/Assets/fruitchute_.unitypackage.meta

- Round Result Scene의 오브젝트를 구성했습니다.
- 1,2,3위의 유저 ID가 화면에 그려집니다.
- 1,2,3위의 플레이어 캐릭터가 화면에 그려집니다.
- #74

[Feat] Round Result Scene 오브젝트 구성

---

JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/LoadingSceneSplashArtCard.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/LoadingSceneSplashArtCardPooler.cs
JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity
JKC_Fallguys/Assets/Huiji/Scripts/UI/Model/RoundResultSceneModel.cs
JKC_Fallguys/Assets/Jinsoo/etc/_legendHoop.unitypackage.meta
JKC_Fallguys/Assets/Jinsoo/etc/fruitchute_.unitypackage.meta
JKC_Fallguys/Assets/Resources/Prefabs/Scene/04_GameLoading/LoadingSceneSplashArtCard.prefab
JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset

- GameLoading Scene의 Card UI Animation을 해상도에 맞게 변경했습니다.
- PlatinioTween 라이브러리 사용
> 부모 Canvas 기준으로 움직이게 하기위하여 PlatinioTween라이브러리를 사용했습니다. 파라미터로 부모 Canvas를 지정해줄 수 있습니다.
- 생성 위치를 anchoredPosition으로 변경
> 부모 Canvas 기준으로 생성 포지션을 정해주기 위하여 anchoredPosition으로 생성 position을 설정합니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/74e730fa-05a2-4c7f-b74a-6affb156d162
- #108 
---
- 하나의 함수로 작성할 수 있는 걸 …

[Fix] Card UI Move Animation Fix

---

JKC_Fallguys/Assets/3_Art/SkyBox/ColorSkies/Skies/Sky_2.mat
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/Legend_Hoop/Legend_Hoop.unity

- Skybox를 배치했습니다.
- Skybox를 배치했습니다.
> 게임에 태를 예쁘게 만들기 위해서 했습니다.

후프의 전설 Skybox를 배치함

---

JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbySceneInitializer.cs
JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
JKC_Fallguys/Assets/2_Scenes/02_MatchingStandby.unity
JKC_Fallguys/Assets/3_Art/Animation/Controller/LobbySceneFallguyAnimator.controller
JKC_Fallguys/Assets/3_Art/Animation/Controller/LobbySceneFallguyAnimator.controller.meta
JKC_Fallguys/Assets/Jinsoo/LobbySceneFallguyController.cs
JKC_Fallguys/Assets/Jinsoo/LobbySceneFallguyController.cs.meta
JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/LobbyBackgroundImage.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/LobbySceneFallGuy.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/01_Lobby/LobbySceneFallGuy.prefab.meta

- Lobby씬이 시작되면, 폴가이가 화면 밖 중앙아래서부터 올라오는 연출이 추가되었습니다
- 애니메이션을 플레이할 프리팹을 만들어, 로드해주었습니다
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005202/637725bb-9362-4a96-9754-715a73c7d240
- #127 
---
- …

[Feat] Lobby 씬의 중앙에 Idle 애니메이션을 루프하는 폴가이 프리팹 추가

---

JKC_Fallguys/Assets/Resources/Fruit_Apple.prefab
JKC_Fallguys/Assets/Resources/Fruit_Banana.prefab
JKC_Fallguys/Assets/Resources/Fruit_Log.prefab
JKC_Fallguys/Assets/Resources/Fruit_Orange.prefab
JKC_Fallguys/Assets/Resources/Fruit_Strawberry.prefab
JKC_Fallguys/Assets/Resources/Fruit_Watermelon.prefab

- 과일대포 맵의 과일들이 이제 탄성에 의해 튀어오르게 됩니다
- 과일들에게 공기저항을 주어 좀 더 느릿한 움직임을 연출하였습니다
- 탄성을 위하여 FruitPhysicsMaterial을 생성하였습니다
> Bounciness 값을 1로 주어 탄성을 주었습니다
- Rigidbody의 공기저항을 추가하였습니다
> 0.1을 주어 공중에서 좀 더 천천히 떨어지게 연출하였습니다
- Before
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005202/3586af60-1491-42da-8ffe-8674348b5c20
- After
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005202/9e06c2e9-e930-4c4c-95f7-ea612b3c5449
- #126 
---
- 과도하게 모듈화 되어 있진 …

[Feat] FruitChute의 과일들 탄성 추가

---

JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelPresenter.cs.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelView.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelView.cs.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelViewController.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelViewController.cs.meta
JKC_Fallguys/Assets/Huiji/Scenes/Config.unity
JKC_Fallguys/Assets/Huiji/Scenes/Config.unity.meta
JKC_Fallguys/Assets/Photon.meta
JKC_Fallguys/Assets/Photon/PhotonLibs.meta
JKC_Fallguys/Assets/Photon/PhotonLibs/Metro.meta
JKC_Fallguys/Assets/Photon/PhotonLibs/netstandard2.0.meta

- 설정 버튼과 설정 패널 오브젝트를 구성합니다.
- #118 
---

[Feat] Configs 게임오브젝트 구성

---

JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/JumpClub.unity
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Ground_Support.mat
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Ground_Support.mat.meta
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Skybox.meta
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Skybox/Hdri setup.txt
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Skybox/Hdri setup.txt.meta
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Skybox/PlanetaryEarth4k.hdr.meta
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Skybox/PlanetaryEarth4k.mat
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Material_JumpClube/Skybox/PlanetaryEarth4k.mat.meta
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Prefabs/LowerBarCenterAxies - Big.prefab
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Prefabs/PinkLowerBar.prefab

- Ground 하단 지지대를 만들었습니다.
- Skybox를 배치했습니다.

[Feat] Ground하단 부분 제작, Skybox 배치 완료

---

JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelView.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/ConfigPanelViewController.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterConfigPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
JKC_Fallguys/Assets/Huiji/Scenes/Config.unity

- 설정 버튼을 누르면 설정 패널이 팝업됩니다.
- 설정 패널의 Close 버튼을 누르면 설정 패널이 비활성화 됩니다.
- Current Lobby State Enum으로 상태 체크
>  State를 체크해서 Settings 상태일때 설정 패널을 팝업시키고 Settings 상태가 아니면 설정 패널을 비활성화 합니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/6a3dcda9-2496-487b-b532-7d6510debc4c
- #117 
---
- [주석이 작성되어 …

[Feat] 환경설정 UI MVRP 스크립트 작성

---

JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/GoalCollider.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/GameLoadingSceneManager.cs
JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/ConveyorBelt.cs
JKC_Fallguys/Assets/2_Scenes/00_Login.unity
JKC_Fallguys/Assets/Jinsoo/LobbySceneManager.cs
JKC_Fallguys/Assets/Jinsoo/LobbySceneManager.cs.meta
JKC_Fallguys/Assets/Jinsoo/StageDataManager.cs
JKC_Fallguys/Assets/Jinsoo/StageDataManager.cs.meta
JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageManager.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/StageManager.prefab.meta
JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
JKC_Fallguys/ProjectSettings/BurstAotSettings_WebGL.json
JKC_Fallguys/ProjectSettings/TimelineSettings.asset

- 룸이 생성되고 게임이 시작되면, 인 게임 내의 플레이어들의 정보를 관리할 StageDataManager를 구현하였습니다
- StageDataManager에 접근 권한은 마스터 클라이언트만이 가지고 있습니다
> 네트워크 기반의 게임에서는, 일관된 게임 상태를 유지하기 위해 모든 게임 로직을 모든 클라이언트에서 동일하게 실행하게 되면 여러 문제가 발생할 수 있습니다
따라서 로직의 주요 부분을 마스터 클라이언트에서만 실행하도록 설계하고, 그 상태를 다른 클라이언트에 전송하여 모든 클라이언트의 게임 상태를 동기화했습니다
- StageDataManager를 Singleton 패턴으로 구현하였습니다
> 해당 클래스의 인스턴스는, 각 게임의 라운드가 진행될 때마다 그 결과를 저장하고 있습니다
이를 통하여, 중간 결산 혹은 게임의 결과창의 연출이 달라지기 때문에 신이 로드되더라도 파괴되지 않고, 단 하나의 인스턴스만을 가질 수 있는 Singleton으로 구현하였습니다
- StageDataManager는 Lobby 씬으로 이동하게 되면 파괴됩니다
> 더 이상 사용할 필요가 없기 때문에 파괴합니다
- #136 
---
- …

[Feat] StateDataManager 구현

---

JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneFallguyController.cs
JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/CharacterCustomization/CustomizationPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/ConfigPanel/SettingsPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterConfigPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingStandbyPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayPresenter.cs.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayView.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayView.cs.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayViewController.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayViewController.cs.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/PlayerNamePlatePresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/TopButtonListPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
JKC_Fallguys/Assets/Huiji/Scenes/Config.unity
JKC_Fallguys/Assets/Resources/UI/Global/Pattern/UI_ZigZagTileablePattern.png.meta
JKC_Fallguys/Assets/Resources/UI/Global/Texture2D_UI_Global_InputKeyCode.png.meta

- Settings Panel에서 게임 설명 버튼을 누르면 HowToPlay Panel이 활성화됩니다.
- HowToPlay Panel에서 확인 버튼을 누르면 설명 Image와 Text가 바뀝니다.
- 보여줄 Image와 Text를 다 보여주고 나서 버튼을 누르면 다시 Settings Panel로 돌아갑니다.
- 모델이 팝업될 Image를 결정할 인덱스를 가지고 있습니다.
> 확인 버튼을 클릭할때마다 모델이 갖고 있는 Image의 Index를 늘려줍니다.
- Image의 인덱스가 바뀔때마다 팝업되는 Text의 Index도 변합니다.
- 버튼을 3번 클릭했다면 작업을 초기화하고 Current State를 Settings로 설정합니다.
> Current State가 Settings로 설정됨에 따라 Settings Panel이 활성화 됩니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/20e2ce5c-c3e3-4d54-bb0e-c8c516e96a34
- #121 
---
- 다른 객체를 참조할 때, …

[Feat] HowToPlay Panel 구현

---

JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume.meta
JKC_Fallguys/Assets/Jinsoo/Customization.unity

- A,S,D,W 키 또는 방향키로 버튼을 선택할 수 있습니다.
- Button의 Navigation기능 사용
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/ec6103b0-ca78-478a-8b51-03847733fe3c
- #167 
---
- Assert()로 사전 조건과 사후 조건을 모두 …

[Feat] Costume UI Button Navigation

---

JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/System/Manager/DataManager.cs

- 이제 반환 타입이 제네릭인 Json을 로드할 수 있는 함수가 추가되었습니다
- Json을 로드하는 제네릭 함수가 추가되었습니다
> 스태틱 클래스인 DataManager에 추가되었습니다
- #181 
---
- …

[Feat] Json 파일을 로드하는 제네릭 함수 추가

---

JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/LobbySceneFallguyController.cs
JKC_Fallguys/Assets/1_Scripts/System/Manager/DataManager.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeData.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumePresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeView.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeViewController.cs
JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
JKC_Fallguys/Assets/Jinsoo/Customization.unity
JKC_Fallguys/Assets/Resources/Costume/Abyss.asset
JKC_Fallguys/Assets/Resources/Costume/Blue.asset
JKC_Fallguys/Assets/Resources/Costume/Grape.asset
JKC_Fallguys/Assets/Resources/Costume/Lemon.asset
JKC_Fallguys/Assets/Resources/Costume/Melon.asset
JKC_Fallguys/Assets/Resources/Costume/Orange.asset
JKC_Fallguys/Assets/Resources/Costume/Strawberry.asset

- 이제 Costume을 클릭해서 변경하면, 플레이어 텍스처가 변화합니다
- 로직을 이어주었습니다
> 버튼을 클릭하거나 엔터치면 함수가 호출되는데, 여기에서 DataManager가 가진 플레이어 텍스처 인덱스를 변화해줍니다
이 인덱스는, 보통 게임 내 모든 곳에서 자신의 프리팹에 영향을 줍니다 
- #125 
---
- 함수는 하나의 일만 해결하고 …

[Feat] 환경설정 - Costume UI MVRP 스크립트 작성 (프리팹의 색상 변하게)

---

JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStageViewController.cs
JKC_Fallguys/Assets/Huiji/Scenes/StageUI.unity
JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ResultInStageViewController.prefab
JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset

---
PR 전에 아래의 내용을 수행했는지 하나씩 체크해봅시다.
PR 전 템플릿 작성에 대한 안내입니다(https://docs.google.com/document/d/1yVqIAEy9-e0qFmxkUpJXM3pcmbIKL2ZTVfAsqc2bhik/edit#heading=h.ip5t2ifb9bvo)
체크 표시는 []에 x를 넣어 [x]로 만들면 됩니다
PR 전 --- 구분선 안의 내용은 삭제해주세요
---
- Stage에서 Round Result Panel 팝업 후 사라지는 애니메이션을 추가했습니다.
- 팝업 후 3초 뒤에 사라지게 합니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/3cbfd295-6632-4ac9-af47-ce26d04a0cb8
- #202 
---
- 과도하게 모듈화 …

[Feat] Stage에서의 Round Result 팝업 후 사라지는 애니메이션 추가

---

JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
JKC_Fallguys/Assets/2_Scenes/00_Login.unity
JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

- 목록 1
- 목록 2
- 목록 3
- 목록 1
> 이유
- 목록 2
> 이유
- 목록 3
> 이유
이 기능과 관련된 스크린샷을 추가합니다. (동영상 가능)
- #{이슈번호} 
- #{이슈번호}
- #{이슈번호}
---
- 함수는 하나의 일만 …

[Refactor] FruitChute GoalCollider의 로직 수정

---

JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendAxe.cs
JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationPresenter.cs
JKC_Fallguys/Assets/2_Scenes/00_Login.unity
JKC_Fallguys/Assets/2_Scenes/05_RoundResult.unity
JKC_Fallguys/Assets/Jinsoo/PhotonClear.cs

---
PR 전에 아래의 내용을 수행했는지 하나씩 체크해봅시다.
PR 전 템플릿 작성에 대한 안내입니다(https://docs.google.com/document/d/1yVqIAEy9-e0qFmxkUpJXM3pcmbIKL2ZTVfAsqc2bhik/edit#heading=h.ip5t2ifb9bvo)
체크 표시는 []에 x를 넣어 [x]로 만들면 됩니다
PR 전 --- 구분선 안의 내용은 삭제해주세요
---
- [] 임시로 작성한 코드는 모두 제거했나요?
- [] 주석은 충분히 작성했나요?
- [] 실행했을 때, 오류는 없나요?
- [] 커밋 메시지는 [가이드](https://docs.google.com/document/d/1bDgWctGEprMvLzV5OpuZV1-BCnrhVVJ19cd8D9tFArU/edit#heading=h.jgj6vfjils4q)에 맞춰 작성됐나요?
- 목록 1
- 목록 2
- 목록 3
- 목록 1
> 이유
- 목록 2
> 이유
- 목록 3
> 이유
이 기능과 관련된 스크린샷을 추가합니다. (동영상 가능)
- #{이슈번호} 
- #{이슈번호}
- #{이슈번호}
---
- 쓸데없는 …

[Refactor] 코드 리팩토링

---

JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageStart/StageStartPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

- Stage 씬의 CountDown UI에서 사용하는 데이터를 StageSceneModel로 분리하였습니다
- Stage 씬의 CountDown UI에서 사용하는 데이터를 StageSceneModel로 분리하였습니다
> 로직과 데이터를 분리하기 위함입니다
- StageSceneModel.SpriteIndex.Value를 구독하는 방식으로 코드를 리팩토링하였습니다
- 마스터 클라이언트에서 해당 UI의 값을 변경시키는 함수를 RpcTarget.All로 모든 클라이언트에게 보내도록 변경하였습니다
> 동기화를 위해, 마스터 클라이언트에서 값에 영향을 주고, 이를 모든 클라이언트에게 쏘는 방식을 취하였습니다
- #238
---
- [주석이 작성되어 …

[Feat] Stage씬에서의 CountDown 시작 타이밍 동기화

---

JKC_Fallguys/Assets/Jinsoo/HoopTask.unity
JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs
JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs.meta
JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNameView.cs
JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNameView.cs.meta
JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNameViewController.cs
JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNameViewController.cs.meta
JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ObservedPlayerNameViewController.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ObservedPlayerNameViewController.prefab.meta

- 관전 중인 PlayerName을 보여주는 UI 게임오브젝트를 구성하였습니다
- 관전 중인 PlayerName을 보여주는 UI 게임오브젝트를 구성하였습니다
> Prefab으로 제작하였습니다
- #154 
---
- …

[Feat] 관전 시스템 UI 게임오브젝트 구성

---

JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteGoalCollider.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs
JKC_Fallguys/Assets/Jinsoo/ObservedPlayerNamePresenter.cs
JKC_Fallguys/Assets/Jinsoo/PlayerContainer.cs
JKC_Fallguys/Assets/Resources/Prefabs/Stage/FruitChute/MapFruitChute.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/MapHoopLegend.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Stage/JumpClub/MapJumpClub.prefab

- StageDataManager의 변경된 로직을 과거로 롤백했습니다
- #262 
---

[Refactor] StageDataManager 코드 리팩토링 롤백

---

JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterConfigPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/TopButtonListPresenter.cs
JKC_Fallguys/Assets/2_Scenes/01_Lobby.unity
JKC_Fallguys/Assets/2_Scenes/04_GameLoading.unity

- TopButtonListView는 Lobby State가 Customization과 Home일때만 활성화됩니다. 
- EnterSettingsButton은 Lobby State가 Home일때만 활성화됩니다.
- UniRx로 LobbyState를 검사해서 UI의 활성화 여부를 설정합니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/c97ddb2b-8095-44a6-a07b-c600cfbbd405
- #240 
---
- [주석이 작성되어 있는가?](https://learn.microsoft.com/ko-kr/dotnet/csharp/language-reference/xmldo …

[Fix] Lobby UI 활성화 설정

---

JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneEventManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerObserverCamera.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs
JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/AxeController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendAxe.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
JKC_Fallguys/Assets/1_Scripts/System/PhotonCleaner.cs

- HoopLegend맵의 Hoop와 Axe들이 이제 DontDestroyObject로 변했다가, 스테이지가 종료될 때 함께 정리됩니다
- Hoop와 Axe들의 코드가 변경되었습니다
> Awake에서 DontDestroyObject로 변환, 스테이지가 끝날 때 정리합니다
- #282 
---
- Assert()로 …

[Refactor] HoopLegend Hoop, Axe들 DontDestroyObject로 변경

---

JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/CommonHoop.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
JKC_Fallguys/Assets/Jinsoo/StageRepository.cs
JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/Axe.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/CommonHoop.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Stage/HoopLegend/SpecialHoop.prefab

- [x 임시로 작성한 코드는 모두 제거했나요?
- 마스터 클라이언트가 아닌, 하위 클라이언트 들이 HoopController의 참조를 찾지 못하여 StageRepository를 통해 찾을 수 있게 변경하였습니다
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005202/5cbef94e-612e-4177-b368-3fbf98d7b423
- #272 
---
- 코드만으로는 이해하기 어려운 부분에 주석이 작성되어 …

[Bug] 마스터 클라이언트가 아닌 클라이언트로 후프의 전설 후프 통과시 Null reference 발생 해결

---

JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/02_MatchingStandby/PhotonMatchingSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerContainer.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageDataManager.cs
JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/StageInstantiateManager.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

- 관전 상태에 진입시, 현재 관전하고 있는 플레이어의 닉네임이 표시됩니다
- PlayerReferenceManager에 Archieve를 추가하였습니다
> 관전 대상의 정보를 가져올 때 해당 정보를 가져옵니다
- PhotonController에 RpcSetInitialize 함수를 추가하였습니다
> PlayerReferenceManager의 정보를 세팅하는 함수입니다
- #287 
---
- 코드만으로는 이해하기 …

[Feat] ObservedPlayerName UI 로직 연동

---

JKC_Fallguys/Assets/1_Scripts/Player/Player States/FallState.cs
JKC_Fallguys/Assets/1_Scripts/Player/Player States/MovementState.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerAnimation.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
JKC_Fallguys/Assets/1_Scripts/Scene/04_GameLoading/MapSelectionManager.cs

- 점프 후 벽에 부딪힌다면 Fall 상태로 바로 전이되게 코드를 변경하였습니다
- 점프 후 벽에 부딪힌다면 Fall 상태로 바로 전이되게 코드를 변경하였습니다
> 플레이어가 벽에 부딪혔는데도 잠시 떠있는 현상이 있었습니다
이는, 플레이어가 Fall로 전이되기 전 Movement상태가 호출되어서인데
이를 해결하기 위해 공중에 떠있다면 Movement로 전이되어도 바로 Fall로 변하게 하였고
Move함수가 호출되지 않게 바로 return 하였습니다
- #273 
--- …

[Bug] 플레이어가 벽에 부딪히는 경우, 바로 떨어지지 않고 멈칫했다가 떨어지는 버그 해결

---

JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PlayerContainer.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ExitButton/ExitButtonPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelPresenter.cs
JKC_Fallguys/Assets/2_Scenes/03_Stage.unity
JKC_Fallguys/Assets/Resources/Prefabs/Scene/03_Stage/UI/ExitButtonViewController.prefab

- Stage 씬에 EventSystem을 추가하였습니다
- Stage 씬에 EventSystem을 추가하였습니다
> EventSystem이 없어 버튼 클릭이 안되던 현상을 수정하였습니다
- #309 
---
- …

[Fix] Stage씬 내에서 Exit Button 클릭시 아무런 동작이 안하는 현상 수정

---

JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Scripts_JumpClub/LowerBar.cs
JKC_Fallguys/Assets/Jinsoo/UnixTimeHelper.cs
JKC_Fallguys/Assets/Jinsoo/UnixTimeHelper.cs.meta
JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset

- UnixTime을 이용하는 UnixTimeHelper클래스를 추가하였습니다
- LowerBar 클래스의 내용을 리팩토링 하였습니다
- UnixTime을 이용하는 UnixTimeHelper클래스를 추가하였습니다
> 전역적인 이벤트를 진행할 때, 단순히 마스터 클라이언트가 메시지를 내보내는 것은 오차가 있을 수 있습니다
이를 각 클라이언트가 동시에 시작하게 하기 위해, 외부 시계인 유닉스 타임을 사용합니다
- LowerBar 클래스의 내용을 리팩토링 하였습니다
> 좀 더 직관적인 변수명을 사용하고, 코드의 수를 줄였습니다
- #320 
---
- [주석이 작성되어 …

[Feat] UnixTimeHelper 클래스 추가

---

JKC_Fallguys/Assets/1_Scripts/Scene/01_Lobby/AudioManager.cs
JKC_Fallguys/Assets/1_Scripts/System/LobbyAudioScheduler.cs

- AudioManager를 통해 플레이어 프리팹이 내는 사운드를 제외한 사운드를 관리합니다.
- AudioManager 클래스에 Play, ScheduleLoopPlayback, Clear 메소드를 추가하였습니다.
> Play 메소드: 특정 사운드를 재생하는 기능을 제공합니다.
ScheduleLoopPlayback 메소드: 루프 음악 재생을 스케줄링하는 기능을 제공합니다. Intro 클립 이후에 Loop 클립을 재생합니다.
Clear 메소드: 모든 오디오 소스를 초기화하고 재생 중인 사운드를 중지하는 기능을 제공합니다.
- #264 
---
- [주석이 작성되어 …

[Refac] AudioManager 재구성

---

JKC_Fallguys/Assets/1_Scripts/Scene/03_Stage/PhotonStageSceneRoomManager.cs
JKC_Fallguys/Assets/Doik/Kimdoik_Working Pole/JumpClub/Scripts_JumpClub/LowerBar.cs
JKC_Fallguys/Assets/Jinsoo/UnixTimeHelper.cs
JKC_Fallguys/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

- PhotonStageRoomManager의 코드가 변경되었습니다
- PhotonNetwork.Time을 기준으로 서버 시간을 동기화합니다
- PhotonNetwork.Time을 기준으로 서버 시간을 동기화합니다
> 모든 클라이언트는 서버 시간을 동기화하여, 전역적인 이벤트의 처리 시간을 똑같이 가져갑니다
- #322 
---
- 함수는 하나의 일만 …

[Refactor] PhotonNetwork.Time을 이용한 StageRoomManager클래스 리팩토링

---

JKC_Fallguys/Assets/1_Scripts/Manager/ResourceManager.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LobbySceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/Util/LiteralRepository/PathLiteral.cs
JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/PlayerTextureRegistry.cs

- Lobby Scene Initializer의 코드가 수정되었고, 영향을 받는 다른 클래스의 경로도 수정되었습니다
- #328 
---

[Refac] Lobby Scene Initializer 경로 Fix

---

JKC_Fallguys/Assets/1_Scripts/Manager/ResourceManager.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LoginSceneInitializer.cs
JKC_Fallguys/Assets/3_Art.meta

LogIn Scene Initializer 경로를 재구성 했습니다.
- #327 
---

[Refac] LogIn Scene Initializer 경로 재구성

---

JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs

- Stage Scene Initializer의 코드가 수정되었습니다
- #330 
---

[Refac] Stage Scene Initializer 경로 Fix

---

JKC_Fallguys/Assets/1_Scripts/SceneInitializer/RoundResultSceneInitializer.cs
JKC_Fallguys/Assets/3_Art.meta

- RoundResult Scene Initializer의 코드를 수정하였습니다
- #331 
---

[Refac] RoundResult Scene Initializer 경로 Fix

---

JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs

- GameResult Scene Initializer의 코드를 수정하였습니다
- #335 
---

[Refac] GameResult Scene Initializer 경로 Fix

---

JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/MatchingSceneInitializer.cs

---
PR 전에 아래의 내용을 수행했는지 하나씩 체크해봅시다.
PR 전 템플릿 작성에 대한 안내입니다(https://docs.google.com/document/d/1yVqIAEy9-e0qFmxkUpJXM3pcmbIKL2ZTVfAsqc2bhik/edit#heading=h.ip5t2ifb9bvo)
체크 표시는 []에 x를 넣어 [x]로 만들면 됩니다
PR 전 --- 구분선 안의 내용은 삭제해주세요
---
Matching Scene Initializer 경로를 재구성합니다.
- #336 
---
- 모든 public 함수에 주석이 작성되어 …

[Refac] Matching Scene Initializer 경로 재구성

---

JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
JKC_Fallguys/Assets/2_Scenes/06_GameResult.unity

- Stage Scene Initializer의 Initialize Model 함수 내부 구조를 심플하게 만들었습니다
- 해당 동작을, StageDataManager 내부의 Clear함수에 밀어넣었습니다
- #340 
---

[Refac] Stage Scene Initializer에서 StageDataManager 의 데이터를 Clear하는 부분 리팩토링

---

JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameLoadingSceneInitializer.cs
JKC_Fallguys/Assets/3_Art.meta

Loading Scene Initializer 경로 재구성
- #339 
---

[Refac] Loading Scene Initializer 경로 재구성

---

JKC_Fallguys/Assets/1_Scripts/SceneInitializer/MatchingSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/etc/02_MatchingStandby/LineEffectPool.cs
JKC_Fallguys/Assets/1_Scripts/etc/02_MatchingStandby/LineEffectPooler.cs

- MatchingStandby 씬에서 모든 오브젝트들이 씬이 로드될 때 동적으로 생성됩니다
- #342 
---

[Refac] Matching씬에 배치된 게임 오브젝트들을 동적으로 생성하도록 로직 변경

---

JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStageView.cs
JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/GameResultFallGuyDataBinder.cs
JKC_Fallguys/Assets/1_Scripts/UI/Model/StageSceneModel.cs
JKC_Fallguys/Assets/1_Scripts/etc/FirstEmoteState.cs
JKC_Fallguys/Assets/1_Scripts/etc/SecondEmoteState.cs
JKC_Fallguys/Assets/1_Scripts/etc/ThirdEmoteState.cs

- GameResult 씬에서 사용되는 폴가이들의 코드 경로를 수정했습니다
- #350 
---

[Fix] GameResult씬에서 폴가이들의 애니메이터 경로 수정

---

JKC_Fallguys/Assets/1_Scripts/Manager/ResourceManager.cs
JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
JKC_Fallguys/Assets/1_Scripts/Manager/StageInstantiateManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultSetupManager.cs
JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
JKC_Fallguys/Assets/1_Scripts/Util/ResourceRegistry/CountdownSpritesRegistry.cs
JKC_Fallguys/Assets/1_Scripts/etc/01_Lobby/LobbySceneFallguyController.cs
JKC_Fallguys/Assets/1_Scripts/etc/02_MatchingStandby/MatchingSceneFallguyController.cs

- ResourceManager에 존재하던 책임에 맞지 않는 필드를 적절하게 분배하였습니다
- #364 
---

[Refac] ResourceManager 정리

---

JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonTimeHelper.cs

- PhotonStageRoomManager에서의 동기화 관련 로직이 변경되었습니다
- PhotonStageRoomManager클래스의 코드가 PhotonTimeHelper를 이용하도록 변경하였습니다
> 전역적으로 동기화 관련 로직은 중복되는 점이 있습니다
이를 클래스로 분리하였고, 리팩토링 하였습니다
- #370 
---
- 함수는 하나의 일만 해결하고 …

[Refac] PhotonStageRoomManager의 동기화 로직을 PhotonTimeHelper를 이용하여 리팩토링

---

JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonTimeHelper.cs

- PhotonTimeHelper가 이제 모든 클라이언트에서 DontDestroyObject로 만들어집니다
- PhotonTimeHelper 내부에 Initialize 함수를 추가하였습니다
> 초기화하며 Rpc로 모든 클라이언트에서 자신을 StageRepository의 자식으로 만들도록 설정하였습니다
- #375 
---
- 함수는 하나의 일만 해결하고 …

[Fix] PhotonTimeHelper를 DontDestroyObject로 만들기

---

JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
JKC_Fallguys/Assets/1_Scripts/Manager/StageInstantiateManager.cs
JKC_Fallguys/Assets/1_Scripts/Manager/StageManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhotonController.cs
JKC_Fallguys/Assets/1_Scripts/Player/PlayerReferenceManager.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameLoadingSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LobbySceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/MatchingSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/SceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/StageSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/Stage/PlayerObserverCamera.cs
JKC_Fallguys/Assets/1_Scripts/UI/05_RoundResult/RoundResultPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/Model/RoundResultSceneModel.cs

- StageManager에 PlayerRepository와 ObjectRepository를 생성합니다
- 해당 게임오브젝트를 통하여 참조를 접근할 수 있게 구성하였습니다
- PlayerRepository를 구현하였습니다
> 해당 저장소에 스테이지가 시작될 때 플레이어를 생성하고, 스테이지가 끝날 때 모든 자식오브젝트를 삭제합니다
- #367 
---
- …

[Feat] StageDataManager의 PlayerContainer동적 생성

---

JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/VolumeSettings.cs

- Configs UI 팝업 시 이전게임에서 설정한 Volume Value Text로 설정되게 수정했습니다.
- PlayerPrefs에 저장하고 있는 로직을 OnDisable에서 OnValueChange로 변경
> Lobby Scene으로 넘어가면서 Configs UI들이 비활성화 되면서 OnDisable을 호출하고 잘못된 값이 PlayerPrefs에 저장
때문에 Slider의 값이 변화될때 PlayerPrefs에 값을 저장하게 변경
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/1d260128-c0ca-4804-a6b3-2415c3813878
- #373 
---
- [주석이 …

[Fix] Configs UI 팝업 시 이전게임에서 설정한 Volume Value Text로 설정되게 Fix

---

JKC_Fallguys/Assets/1_Scripts/Manager/GameLoadingSceneManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneEventManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonStageSceneRoomManager.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/GameResultSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/SceneInitializer/RoundResultSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/UI/00_Login/LoginPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingPresenter.cs
JKC_Fallguys/Assets/1_Scripts/Util/Helper.meta
JKC_Fallguys/Assets/1_Scripts/Util/Helper/SceneChangeHelper.cs
JKC_Fallguys/Assets/1_Scripts/Util/Helper/SceneChangeHelper.cs.meta

- SceneChangeHelper 클래스를 구현하였습니다
- 이제 LoadScene이나 LoadLevel 메서드의 경우, 해당 클래스의 함수를 통해 호출합니다
- SceneChangeHelper 클래스를 구현하였습니다
> 여러곳에서 씬을 로드하는 함수가 퍼져있어서, 트래킹을 쉽게하기 위해 클래스를 하나 만들고 그곳에서 선언한 메소드를 이용하여 씬을 로드합니다
- #387 
---
- 코드만으로는 이해하기 어려운 부분에 …

[Feat] SceneChangeHelper 클래스 구현

---

JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/MapHoopLegend.prefab

- HoopLegend맵의 외벽의 레이어를 Ground로 변경하였습니다
- 더이상 밖으로 떨어지지 않습니다
- #393 
---

[Fix] HoopLegend맵의 외벽 물리 매트릭스 변경

---

JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/LowerBar.cs
JKC_Fallguys/Assets/Resources/Materials/Physics/LowerBarPhysicsMaterial.physicMaterial
JKC_Fallguys/Assets/Resources/Materials/Physics/LowerBarPhysicsMaterial.physicMaterial.meta
JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/JumpClub/MapJumpClub.prefab

- JumpClub의 LowerBar를 수정하였습니다
- 부딪힌 플레이어에게 힘을 가하는 방식을 사용하여, 일정 이상 속도로 봉이 회전할 때 플레이어가 부딪힌다면, 팽이처럼 돌며 떨어집니다
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005202/d284a67d-92f6-4a7e-9936-0e4815bde868
- #390 
---
- 함수는 하나의 …

[Fix] JumpClub맵의 LowerBar 수정

---

JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/JumpClub/JumpClubDeadZone.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ResultInStage/ResultInStagePresenter.cs

- JumpClubDeadZone의 코드가 수정되었습니다
- JumpClubDeadZone의 코드가 수정되었습니다
> 점프클럽에서 제한 시간이 되지 않은 상태에서 마지막으로 사망하는 플레이어의 경우 바로 종료 상태로, 이미 죽은 사람은 종료 상태로 만들어 UI가 한번 더 팝업되어 생동감을 주었습니다
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005202/d160a4e2-5b0f-4a21-bde5-32cca7e7096a
- #394 
---
- [주석이 작성되어 있는가?](https://learn.microsoft.com/ko-kr/dotnet/csharp/language-reference/ …

[Feat] JumpClubController 클래스에 코드 추가

---

JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/SpecialHoop.cs
JKC_Fallguys/Assets/1_Scripts/Stage/PlayerObserverCamera.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/CharacterCustomization/CustomizationView.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigReturnButtonView.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingView.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/PlayerNamePlatePresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/PlayerNamePlateView.cs
JKC_Fallguys/Assets/1_Scripts/UI/02_Matching/ExitMatchingPanelView.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNameView.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelView.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/GameLoadingMainPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/GameLoadingMainPanelView.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationView.cs
JKC_Fallguys/Assets/1_Scripts/UI/06_GameResult/ResultView.cs
JKC_Fallguys/Assets/Resources/Prefabs/UI/04_GameLoading/MapInformationViewController.prefab

- View를 상속받는 클래스 중, 쓸데없는 요소들을 삭제하였습니다
- View를 상속받는 클래스 중, 쓸데없는 요소들을 삭제하였습니다
> 사용하지 않는 객체의 코드를 삭제하여, 코드를 줄였습니다
- #406 
---
- …

[Refac] View 클래스를 상속받는 스크립트에서 필요없는 코드 삭제

---

JKC_Fallguys/Assets/1_Scripts/Player/PlayerPhysicsController.cs
JKC_Fallguys/Assets/1_Scripts/Player/States/Dive/DiveStartState.cs
JKC_Fallguys/Assets/1_Scripts/Player/States/Jump/JumpSubState.cs
JKC_Fallguys/Assets/Resources/Character/Animation/Player.controller
JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab

jump와 dive키를 동시에 눌렀을때 강한 힘으로 점프하는 현상을 해결했습니다.
- JumpState에서 DiveHeightForce를 0으로 설정
> JumpState에서 Dive의 위로 가하는 힘을 더하지 않게 하기 위해 DiveHeightForce를 초기화했습니다.
- Dive State를 빠져나갈때 DiveHeightForce를 복구
Uploading 녹화_2023_07_11_18_23_51_179.mp4…
- #242 
---
- 모든 public 함수에 주석이 …

[Fix] jump와 dive키를 동시에 눌렀을때 강한 힘으로 점프하는 현상 해결

---

JKC_Fallguys/Assets/1_Scripts/Player/PlayerInputController.cs
JKC_Fallguys/Assets/Resources/Prefabs/Player.prefab

- 카메라 감도가 낮아졌습니다.
- 
- PlayerInputController 스크립트에 카메라 감도 조절 로직을 구현햇습니다.
> 인스펙터 창에서 mouseSensitivity값을 조절해서 감도를 조절할 수 있습니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/ba67c3cb-cbe1-43f4-a1ca-d92cea4989ae
- #420 
---
- 모든 public 함수에 …

[Feat] 카메라 감도를 조절하는 로직 구현

---

JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumeButtonAction.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Costume/CostumePresenter.cs
JKC_Fallguys/Assets/Resources/ScriptableObject/Grape.asset
JKC_Fallguys/Assets/Resources/ScriptableObject/Lemon.asset
JKC_Fallguys/Assets/Resources/ScriptableObject/Melon.asset
JKC_Fallguys/Assets/Resources/ScriptableObject/Orange.asset
JKC_Fallguys/Assets/Resources/ScriptableObject/Strawberry.asset

- 키보드로 버튼간 이동할때 선택된 버튼의 이름이 CostumeNameText에 출력되게 했습니다.
- Button의 OnSelect에서 Text를 변경하는 로직을 수행했습니다.
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/f5c00a12-a033-4dd4-ac16-68ec32d13053
- #419 
---
- 코드만으로는 …

[Fix] 버튼의 OnSelect에서 CostumeNameText가 변경되게 수정

---

JKC_Fallguys/Assets/1_Scripts/etc/01_Lobby/LobbySceneFallguyController.cs
JKC_Fallguys/ProjectSettings/ProjectSettings.asset

- Lobby Scene에서 Home, Costumization UI를 번갈아 띄울때 폴가이가 순간이동하지 않고 부드럽게 움직입니다.
- Home, Costumization 버튼을 클릭할때 cancelToken.Cancel 실행.
> 폴가이는 UniTask로 버튼이 눌릴때마다 움직입니다. 움직이는 도중 버튼이 눌리면 이전 UniTask의 실행을 취소합니다. 
https://github.com/KIA-PROGRAMMING-38/JKC-FallguysProject/assets/120005259/e12e187a-d13f-45f1-9296-ec22aab0c3f6
- #421 
---
- [주석이 작성되어 …

[Fix] Lobby Scene Fall Guy가 움직일때 다른 UI를 띄우면 움직임을 Cancel하도록 수정

---

JKC_Fallguys/Assets/1_Scripts/Photon/PhotonInitializeManager.cs
JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
JKC_Fallguys/Assets/1_Scripts/Stage/FruitChute/FruitChuteController.cs
JKC_Fallguys/Assets/1_Scripts/Stage/HoopLegend/HoopLegendController.cs

- 룸 동기화 로직을 개선하였습니다
- PhotonMatchingSceneEventManager 코드를 수정하였습니다
> 매칭이 시작되면, 3초간 먼저 룸을 찾습니다
이후, 룸이 없다면 생성하고, 룸이 이미 서버에 존재한다면 참여합니다
거기에서도 룸 입장에 실패한다면, Lobby로 돌아갑니다
- #416 
---
- …

[Refac] 룸 동기화 로직 개선

---

JKC_Fallguys/Assets/1_Scripts/Photon/PhotonMatchingSceneEventManager.cs
JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState.cs
JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameCompletion.cs
JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_GameInProgress.cs
JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_PlayersReady.cs
JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_RoundCompletion.cs
JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_Transitioning.cs
JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_WaitingForPlayers.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingPresenter.cs

- StageState의 AddToDictionary함수를 AddToSequenceActionDictionary로 변경하였습니다
- 추상 메서드의 이름을 변경하였습니다
> 함수 이름이 좀 더 명확하게 역할을 나타낼 수 있도록 변경하였습니다
- #448 
---
- Assert()로 사전 조건과 사후 조건을 모두 …

[Style] StageState의 AddToDictionary함수를 AddToSequenceActionDictionary로 변경

---

JKC_Fallguys/Assets/2_Scenes/03_Stage.unity
JKC_Fallguys/Assets/3_Art.meta
JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/FruitChute/MapFruitChute.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/HoopLegend/MapHoopLegend.prefab
JKC_Fallguys/Assets/Resources/Prefabs/Object/03_Stage/JumpClub/MapJumpClub.prefab
JKC_Fallguys/Assets/Resources/Sprites/SkyBox/ColorSkies/Skies/Sky_2.mat

- 명암이 옅어졌습니다.
- Direction Light를 여러개 배치함으로써 명암이 짙은 현상을 해결했습니다.
- #425 
- 
---

[Style] 명암이 짙은 현상을 해결

---

JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LobbySceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelPresenter.cs.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelView.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelView.cs.meta
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelViewController.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelViewController.cs.meta
JKC_Fallguys/Assets/1_Scripts/UI/Model/LobbySceneModel.cs
JKC_Fallguys/Assets/2_Scenes/00_Login.unity
JKC_Fallguys/Assets/Resources/Prefabs/UI/00_Login/LoginPanelViewController.prefab
JKC_Fallguys/Assets/Resources/Prefabs/UI/01_Lobby/LobbyConnectionWarningPanelViewController.prefab
JKC_Fallguys/Assets/Resources/Prefabs/UI/01_Lobby/LobbyConnectionWarningPanelViewController.prefab.meta

- Lobby씬에서 Matching 씬으로 전환 시도할 때, Lobby가 아니라면 UI 팝업으로 상태를 알립니다
- #446 
---

[Feat] Lobby씬에서 Matching 씬으로 전환 시도할 때, Lobby가 아니라면 UI 팝업으로 상태 알리기

---

JKC_Fallguys/Assets/1_Scripts/SceneInitializer/LoginSceneInitializer.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsPresenter.cs

- 해상도를 전체화면으로 변경하였습니다
. (동영상 가능)
- #452 
---

[Chore] 플레이 화면 전체화면으로 변경

---

JKC_Fallguys/Assets/1_Scripts/Manager/StageDataManager.cs
JKC_Fallguys/Assets/Resources/Materials/HoopLegend/Ground.mat
JKC_Fallguys/Assets/Resources/Materials/JumpClub/Ground.mat
JKC_Fallguys/ProjectSettings/EditorBuildSettings.asset
JKC_Fallguys/ProjectSettings/ProjectSettings.asset

- JumpClub, HoopLegend 바닥 색이 변경되었습니다
- #458 
---

[Chore] JumpClub, HoopLegend 바닥 색 변경

---

JKC_Fallguys/Assets/Resources/Materials/ConveyorBeltShaderGraph.shadergraph
JKC_Fallguys/Assets/Resources/Materials/FruitChute/Canon_HotAirBallon.mat
JKC_Fallguys/Assets/Resources/Materials/FruitChute/ConveyorBeltShaderMaterial.mat

[Chore] 컨베이어 벨트 밝기 조절, 열기구 메탈릭 조정

---

JKC_Fallguys/Assets/1_Scripts/Player/States/Grab/AttempingGrabState.cs

[Style] Delete Grab

---

JKC_Fallguys/Assets/1_Scripts/Manager/MapSelectionManager.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsPresenter.cs

- 1920 * 1080일 시에만 해상도가 풀스크린으로 변경되게 하였습니다
- #465 
---

[Chore] Config 해상도 변경

---

JKC_Fallguys/Assets/Resources/Prefabs/UI/06_GameResult/GameResultBackgroundImage.prefab

- GameResult씬 Background 크기 조절
---

[Chore] GameResult씬 Background 크기 조절

---

JKC_Fallguys/Assets/1_Scripts/Manager/StageManager.cs
JKC_Fallguys/Assets/1_Scripts/Stage/PlayerContainer.cs
JKC_Fallguys/Assets/1_Scripts/Stage/StageState/StageState_Transitioning.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/CharacterCustomization/CustomizationPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Configs/ConfigsPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterConfigPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/EnterMatchingPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/HowToPlay/HowToPlayPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/LobbyConnectionWarningPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/PlayerNamePlatePresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/Settings/SettingsPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/01_Lobby/TopButtonListPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/02_Matching/ExitMatchingPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/ObservedPlayerNamePresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/RemainingTime/RemainingTimePresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/03_Stage/StageExitPanel/StageExitPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/GameLoadingMainPanelPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/HorizontalRendererPresenter.cs
JKC_Fallguys/Assets/1_Scripts/UI/04_GameLoading/MapInformationPresenter.cs
JKC_Fallguys/Assets/1_Scripts/Util/Helper/GameObjectHelper.cs

- StageManager클래스 코드가 리팩토링되었습니다
- StageManager클래스 내부의 게임 오브젝트를 만들어 자식으로 붙이는 코드를 Helper함수로 빼내었습니다
> 코드 가독성을 높이기 위하여, 모듈화를 진행하였습니다
- #472 
---
- Assert()로 사전 조건과 사후 조건을 모두 체크하고 …

[Refac] StageManager 코드 리팩토링
